### ISSUE TITLE
Syntax error or access violation: 1066 Not unique table/alias

### ISSUE THREAD

**Issue by Keinstah** [alohajaycee/laravel-traversify#2]
I was trying to use the search feature then I encountered this issue.

```
Syntax error or access violation: 1066 Not unique table/alias
```

**How to reproduce:** 
1. Add `Traversify` trait in modelA
2. Add property `$autoload = ['modelB']` in ModelA
3. Add property `$search = ['modelB.prop']` in ModelA
4. Create query to join two model then traversify it `ModelA.leftJoin('modelB...').traversify($request)`

**Comment by jayceedaily** [comment]
This was fixed on release v2.2.14
